export const VISIBLE_MARKER_COLOR = 0x00ff00, HIDDEN_MARKER_COLOR = 0xff0000
export const MARKER_INDICATOR_UPDATE_INTERVAL = 100

export const SHADER_PROPERTY_PREFIX = 'p_'
export const SHADER_COLOR_MAP = 'cm_colorMap'